export const LOVEPARKS_LOADING = 'LOVEPARKS_LOADING';
export const LOVEPARKS_FAILED = 'LOVEPARKS_FAILED';
export const ADD_LOVEPARKS = 'ADD_LOVEPARKS';

export const HISTORYPARKS_LOADING = 'HISTORYPARKS_LOADING';
export const HISTORYPARKS_FAILED = 'HISTORYPARKS_FAILED';
export const ADD_HISTORYPARKS = 'ADD_HISTORYPARKS';

export const ORDERPARKS_LOADING = 'ORDERPARKS_LOADING';
export const ORDERPARKS_FAILED = 'ORDERPARKS_FAILED';
export const ADD_ORDERPARKS = 'ADD_ORDERPARKS';

export const INFOUSER_LOADING = 'INFOUSER_LOADING';
export const INFOUSER_FAILED = 'INFOUSER_FAILED';
export const ADD_INFOUSER = 'ADD_INFOUSER';

export const CHANGE_LOADING = 'CHANGE_LOADING';
export const CHANGE_FAILED = 'CHANGE_FAILED';
export const ADD_CHANGE = 'ADD_CHANGE';

export const DELETEUSER_LOADING = 'DELETEUSER_LOADING';
export const DELETEUSER_FAILED = 'DELETEUSER_FAILED';
export const ADD_DELETEUSER = 'ADD_DELETEUSER';

export const DELETELOVEPARK_LOADING = 'DELETELOVEPARK_LOADING';
export const DELETELOVEPARK_FAILED = 'DELETELOVEPARK_FAILED';
export const ADD_DELETELOVEPARK = 'ADD_DELETELOVEPARK';

export const DELETEHISTORYPARK_LOADING = 'DELETEHISTORYPARK_LOADING';
export const DELETEHISTORYPARK_FAILED = 'DELETEHISTORYPARK_FAILED';
export const ADD_DELETEHISTORYPARK = 'ADD_DELETEHISTORYPARK';

export const DELETEORDERPARK_LOADING = 'DELETEORDERPARK_LOADING';
export const DELETEORDERPARK_FAILED = 'DELETEORDERPARK_FAILED';
export const ADD_DELETEORDERPARK = 'ADD_DELETEORDERPARK';