export const ALLPARKS_LOADING = 'ALLPARKS_LOADING';
export const ALLPARKS_FAILED = 'ALLPARKS_FAILED';
export const ADD_ALLPARKS = 'ADD_ALLPARKS';

export const BESTPARKS_LOADING = 'BESTPARKS_LOADING';
export const BESTPARKS_FAILED = 'BESTPARKS_FAILED';
export const ADD_BESTPARKS = 'ADD_BESTPARKS';

export const CHEAPPARKS_LOADING = 'CHEAPPARKS_LOADING';
export const CHEAPPARKS_FAILED = 'CHEAPPARKS_FAILED';
export const ADD_CHEAPPARKS = 'ADD_CHEAPPARKS';

export const NEARPARKS_LOADING = 'NEARPARKS_LOADING';
export const NEARPARKS_FAILED = 'NEARPARKS_FAILED';
export const ADD_NEARPARKS = 'ADD_NEARPARKS';

export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const PARK_STATUS_LOADING = 'PARK_STATUS_LOADING';
export const PARK_STATUS_FAILED = 'PARK_STATUS_FAILED';
export const ADD_PARK_STATUS = 'ADD_PARK_STATUS';

export const PARK_INFO_LOADING = 'PARK_INFO_LOADING';
export const PARK_INFO_FAILED = 'PARK_INFO_FAILED';
export const ADD_PARK_INFO = 'ADD_PARK_INFO';

export const ADD_REPORT = "ADD_REPORT";

export const USER_LOADING = 'USER_LOADING';
export const USER_FAILED = 'USER_FAILED';
export const ADD_USER = 'ADD_USER';

export const USERLIST_LOADING = 'USERLIST_LOADING';
export const USERLIST_FAILED = 'USERLIST_FAILED';
export const ADD_USERLIST = 'ADD_USERLIST';

export const OWNERLIST_LOADING = 'OWNERLIST_LOADING';
export const OWNERLIST_FAILED = 'OWNERLIST_FAILED';
export const ADD_OWNERLIST = 'ADD_OWNERLIST';

export const PARKLIST_LOADING = 'PARKLIST_LOADING';
export const PARKLIST_FAILED = 'PARKLIST_FAILED';
export const ADD_PARKLIST = 'ADD_PARKLIST';


export const USERCHART_LOADING = 'USERCHART_LOADING';
export const USERCHART_FAILED = 'USERCHART_FAILED';
export const ADD_USERCHART = 'ADD_USERCHART';

export const RATINGCHART_LOADING = 'RATINGCHART_LOADING';
export const RATINGCHART_FAILED = 'RATINGCHART_FAILED';
export const ADD_RATINGCHART = 'ADD_RATINGCHART';


export const TRANSCHART_LOADING = 'TRANSCHART_LOADING';
export const TRANSCHART_FAILED = 'TRANSCHART_FAILED';
export const ADD_TRANSCHART = 'ADD_TRANSCHART';

export const ADD_SEARCHINFO = 'ADD_SEARCHINFO';

export const ADD_FAVOMARK = 'ADD_FAVOMARK';


export const SET_SNACKBAR = 'SET_SNACKBAR';
// OWNER
export const OWNERPARKS_LOADING = 'OWNERPARKS_LOADING';
export const OWNERPARKS_FAILED = 'OWNERPARKS_FAILED';
export const ADD_OWNERPARKS = 'ADD_OWNERPARKS';

export const PARKINFO_LOADING = 'PARKINFO_LOADING';
export const PARKINFO_FAILED = 'PARKINFO_FAILED';
export const ADD_PARKINFO = 'ADD_PARKINFO';

export const PARKREVIEW_LOADING = 'PARKREVIEW_LOADING';
export const PARKREVIEW_FAILED = 'PARKREVIEW_FAILED';
export const ADD_PARKREVIEW = 'ADD_PARKREVIEW';

export const BOOKLIST_LOADING = 'BOOKLIST_LOADING';
export const BOOKLIST_FAILED = 'BOOKLIST_FAILED';
export const ADD_BOOKLIST = 'ADD_BOOKLIST';

export const PARKSTATUS_LOADING = 'PARKSTATUS_LOADING';
export const PARKSTATUS_FAILED = 'PARKSTATUS_FAILED';
export const ADD_PARKSTATUS = 'ADD_PARKSTATUS';